# Generated by Django 5.2.6 on 2025-09-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expirements_bookcategory_date_videocategory_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpirementVideo',
            new_name='Expirement',
        ),
    ]
