# Generated by Django 5.2.6 on 2025-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_expirementvideo_expirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirement',
            name='text',
        ),
        migrations.AddField(
            model_name='expirement',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expirement',
            name='youtubelink',
            field=models.URLField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
