# Generated by Django 5.2.6 on 2025-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_expirement_text_expirement_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expirement',
            old_name='youtubelink',
            new_name='youtubelink1',
        ),
        migrations.AddField(
            model_name='expirement',
            name='youtubelink2',
            field=models.URLField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expirement',
            name='youtubelink3',
            field=models.URLField(default=1, max_length=1500),
            preserve_default=False,
        ),
    ]
