# Generated by Django 5.2.6 on 2025-09-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_book_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='person',
        ),
    ]
