# Generated by Django 5.2.6 on 2025-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_book_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='min',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
