# Generated by Django 5.2.6 on 2025-10-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_experiment_youtubelink1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classvideo',
            name='min',
        ),
        migrations.RemoveField(
            model_name='classvideo',
            name='text',
        ),
        migrations.AddField(
            model_name='experiment',
            name='link',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videocategory'),
        ),
    ]
