# Generated by Django 5.2.6 on 2025-11-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_experiment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
    ]
