# Generated by Django 5.2.6 on 2025-12-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_video_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassVideo',
        ),
    ]
