# Generated by Django 5.2.6 on 2025-12-07 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_classvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='class_videos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.classcategory')),
            ],
        ),
    ]
