# Generated by Django 5.2.6 on 2025-12-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_classvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
