# Generated by Django 5.2.6 on 2025-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_loginhistory_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classvideo',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='classvideo',
            name='link',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
